### ISSUE TITLE
clib install fails

### ISSUE THREAD

**Issue by phoenixpinpoint** [bonedaddy/ulog#25]
fetch : bonedaddy/ulog:clib.json
       fetch : bonedaddy/ulog:include/colors.h
       fetch : bonedaddy/ulog:include/version.h
       fetch : bonedaddy/ulog:include/logger.h
       fetch : bonedaddy/ulog:src/colors.c
       fetch : bonedaddy/ulog:src/logger.c
       fetch : bonedaddy/ulog:cmake/CMakeLists.txt
        save : ./deps/ulog/logger.c
        save : ./deps/ulog/CMakeLists.txt
        save : ./deps/ulog/colors.h
        save : ./deps/ulog/colors.c
        save : ./deps/ulog/version.h
        save : ./deps/ulog/logger.h
       error : Unable to install package bonedaddy/ulog

**Comment by droughtrye** [comment]
This is resolved by #26 which has been merged.
